# Generated by Django 5.2.6 on 2025-09-29 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.measureunit'),
        ),
    ]
