# Generated by Django 5.2.6 on 2025-09-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_ingredient_measure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='count',
            field=models.BooleanField(default=False),
        ),
    ]
