# Generated by Django 5.2.6 on 2025-09-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_measureunit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='annotations',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
