# Generated by Django 5.2.6 on 2025-10-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_type_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
