# Generated by Django 5.2.6 on 2025-10-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_type_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='abreviation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
