# Generated by Django 5.2.6 on 2025-10-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_measureunit_abreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measureunit',
            old_name='abreviation',
            new_name='abbreviation',
        ),
    ]
