# Generated by Django 5.2.6 on 2025-10-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_ingredient_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealgroupdetail',
            name='meal_group',
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mealgroupdetail',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealgroupdetail',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.dish'),
        ),
        migrations.DeleteModel(
            name='MealGroup',
        ),
    ]
