# Generated by Django 5.2.6 on 2025-10-25 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealgroupdetail',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.dish'),
        ),
    ]
