# Generated by Django 5.2.6 on 2025-11-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_mealgrouptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealgroupdetail',
            name='meal_group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.mealgrouptype'),
        ),
    ]
