# Generated by Django 5.2.6 on 2025-12-18 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_mealgroupdetail_meal_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.dish')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.type')),
            ],
        ),
    ]
