# Generated by Django 5.2.6 on 2025-12-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_photos/'),
        ),
    ]
